### ISSUE TITLE
Strange call by name

### ISSUE THREAD

**Issue by jonmountjoy** [waddlaw/TAPL#94]
Hello!

I wonder if the [call by name evaluation strategy](https://github.com/waddlaw/TAPL/blob/bac5536f32e48eb6bdad9cb05cad0d1ef9ba0b50/subs/lambda-untyped/src/Language/UntypedLambda.hs#L87) is correct:

In particular, it has this line, which definitely looks wrong:

```
reduceCallByName (TmApp t1@(TmApp _ _) t2@(TmApp _ _)) = TmApp (reduceCallByName t1) (reduceCallByName t2)
```

as it reduces two terms at once, which is definitely not a call-by-name thing.

I think the following will actually work, if you replace the entire function with just these lines:

```
reduceCallByName (TmApp (TmLam x old) new) = subst x new old
reduceCallByName (TmApp t1 t2) = TmApp (reduceCallByName t1) t2
reduceCallByName t = t
```

These will also now match E-APP1 and E-APPABS in the operational semantics provided in the answer to 5.3.6.

**Comment by waddlaw** [comment]
Thank you. You are right.
And by the way, I fixed the other strategies as well. See: #96

**Comment by jonmountjoy** [comment]
Excellent.  Thank you!
